model_params:
  epochs: 1
  loss: categorical_crossentropy
  optimizer: adam
  metrics: ['accuracy']

data_params:
  train_data_path: Data\Train
  test_path: Data\Test.csv
  split_ratio: 0.2

artifacts:
  models: Models
  plots: Plots