model_params:
  epochs: 1
  loss: categorical_crossentropy
  optimizer: RmsProp
  metrics: ['accuracy']
  batch_size: 32

data_params:
  train_data_path: Data\Train
  test_path: Data\Test.csv
  split_ratio: 0.2

mlflow_config:
  artificats_dir: artifacts
  experiment_name: Cnn_architechture
  registered_model_name: CNN
  run_name: mlops
  remote_server_uri: http://127.0.0.1:5000
  
prediction_service:
  model_dir: prediction_service\model\